### PR TITLE
Updated to use Tetris's random generator

### PR DESCRIPTION
**Pull request by ambaxter**
Updated to use random generator as described by http://tetris.wikia.com/wiki/Random_Generator

This makes the game slightly more sane.

### CODE REVIEW

**Comment by bvssvni** [comment]
Nice! Merging.

**Comment by bvssvni** [comment]
Ops. You are still working on it. Tell me you're ready!

**Comment by ambaxter** [comment]
Ready!

**Comment by bvssvni** [comment]
Merging.

**Pull request merged**
